### ISSUE TITLE
Proposal: Remove o.load event

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/o-autoinit#14]
I'm not sure this event is used in any origami component.

**Comment by JakeChampion** [comment]
Only techdocs uses this event and we are planning to deprecated/dead techdocs --> https://github.com/Financial-Times/o-techdocs/blob/793129aa152d25ff5413efcb4a819b20e4d93381/src/js/nav.js#L121

**Comment by notlee** [comment]
I was tempted to suggest keeping it, just in case anyone needs it, but no... unlikely... saving a few bytes is nice :)

**Comment by notlee** [comment]
This is done, to be released as part of the major cascade. Closing to keep track of progress. See: https://github.com/Financial-Times/o-autoinit/pull/24
