### ISSUE TITLE
Proposal: Remove code specific for IE

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/o-autoinit#15]
IE has supported DOMContentLoaded since version 9. I don't think we required having this specific IE code anymore.

https://github.com/Financial-Times/o-autoinit/blob/702555469b9e4c8fef1d1c8a0ade7e2bd6dd375b/main.js#L32-L58

**Comment by notlee** [comment]
That’s interesting code. Yes I think that can be removed 👌
